server:
  port: 8090

generator:
  kafka:
    incidents_topic: ${INCIDENTS_TOPIC:INCIDENTS_TOPIC.RQ}
    bootstrap-servers: ${KAFKA_SERVER:localhost:9092}
  incidents:
    count: ${GENERATOR_INCIDENTS_COUNT:1}
    cron: ${GENERATOR_INCIDENTS_CRON_PATTERN:0/5 * * * * *}
    random:
      speed:
        max: 300
        min: 15



